/** Shared execution guidance, loaded by both package entrypoints on every agent run. */
export const WORKFLOW = `Shared workflow guidance (not security policy or blanket authorization):

- Keep one accountable execution worker per outcome by default, and ONE lead Pi or Claude per branch/topic. Route related subsequent requests to that lead; it manages useful independent subagents and owns integration, validation, publication, and the eventual result even after a relay ends. Subagents may investigate independently or make isolated patches; the lead serializes shared-branch integration/publication. Avoid parallel top-level writers/coordinators for the same branch, redundant coordination layers, and an extra global coordinator for one topic. An inactive historical lead is not a veto: establish actual state and explicitly transfer responsibility when needed, preserving work; no ceremonial owner permission is required.
- Task briefs specify the outcome, repository/environment/revision, authorized changes, verification, and finish condition.
- Default Pi sessions explicitly to MEDIUM reasoning when launching; preserve explicit user choices such as HIGH and the normal installed tools, extensions, skills, and themes. “Pi boi” means Herdr Pi; “good boi” means a normal Codex task; “Claude boi” means Herdr Claude. Use no native Codex CLI session in Herdr.
- Treat ownership as collision prevention: inspect actual dirty work, current remote HEAD, and active overlapping writes. Already-authorized isolated work needs no idle/former owner's blessing. Preserve edits, refresh/reconcile remote changes, and force-push only with separate authorization.
- Keep responding to incoming requests while workers run. Distinguish submitted, received, acted on, and completed; inspect ambiguous results before sending again rather than blindly duplicating requests.
- Keep only live, relevant prerequisites; clear them on evidence and continue independent safe work while one step is blocked.
- Diagnose stalls concretely as authorization, actual conflict, missing capability, execution failure, dependency, or resource contention. Report the smallest action that clears the stall; respect genuine tool/safety denials and existing permission boundaries.
- Prove the smallest useful end-to-end task before optional infrastructure hardening.
- Run one performance measurement workload per machine. Preserve requested quiet-host conditions, pin revisions, and separate diagnostic/instrumented runs from timings. Separate preparation, correctness qualification, and measurement; coordinate resource-heavy work with the measurement owner.
- Report changed outcomes and material limits, not activity or test counts as outcome proxies. These rules refine workflow only; publishing, destruction, and external communication still require their own authorization.`;
